### PR TITLE
[Resolves #894] Convert the project to use poetry

### LINKED ISSUE #894: Implement package management and accommodate PEP-517/518
# Package Management / Modernization

## Context

Currently, sceptre is using the setup.py, setup.cfg, and dev/prod requirements.txt files to handle sceptre packaging, dependencies, and publishing.

[PEP-517](https://www.python.org/dev/peps/pep-0517/)
[PEP-518](https://www.python.org/dev/peps/pep-0518/)
[PEP 517 and 518 in Plain English](https://medium.com/@grassfedcode/pep-517-and-518-in-plain-english-47208ca8b7a6)

## Possible Fix

Migrate to use [Poetry](https://github.com/python-poetry/poetry), removing setup.py and MANIFEST.in in favor of the new pyproject.toml standard.

### PR DESCRIPTION
**Pull request by tarkatronic**
The intent here is to change the tooling over to use [poetry](https://python-poetry.org) instead of `setuptools`. This is unfortunately not a small change, especially for a project of this size. However as you can see, it will lead to a great consolidation of tools and files.

Some important things to note:

* Poetry is smart enough to automatically include data files such as the `*.json` that had to be manually included by setuptools.
* `twine` is no longer necessary as we can simply use `poetry publish`.
* Poetry handles all virtualenv matters automatically. So we no longer need to instruct users to construct virtualenvs for development purposes, nor do we need to manually create and manage them for CI.
* Dependency specifications are a bit different with Poetry, and a bit more "modern", [as seen here](https://python-poetry.org/docs/dependency-specification/).
* I have told git (via the `.gitattributes`) file to treat the `poetry.lock` file as binary. This is a fairly standard practice, also followed in the JS community with the `package-lock.json` file. This does two primary things:
  * Tells GitHub to not attempt to display a diff for this file
  * Prevents frequent merge conflicts, since this tends to be a frequently updated file
* I have included `awscli` and all of the Sphinx-related requirements as dev requirements. This means that they will be installed when a developer runs `poetry install`. If that's not desirable, I can remove `awscli`, and move the Sphinx requirements to an "extra", [as seen here](https://github.com/godaddy/tartufo/blob/74291f93d0f33b5279bf6d1f62d2df453658281a/pyproject.toml#L65-L66). This latter part would mean that you would have to run `poetry install -E docs` to get the Sphinx requirements.

Note that I am starting this as a draft PR while I work on it, to show my progress. There will likely need to be significant work done to uplift the CI to work with poetry. I can pretty much guarantee that it WILL NOT pass right now. But luckily, CircleCI [may have an easy way](https://circleci.com/developer/orbs/orb/circleci/python#usage-work-with-poetry) to help facilitate this!

## Checklist for completion of this change

- [x] Set up base poetry config in pyproject.toml
- [x] Update tox to use poetry
- [x] Update Makefile to use poetry
- [x] Update Dockerfile to use poetry
- [x] Update CircleCI to use poetry
- [x] Remove setuptools config

## PR Checklist

- [X] Wrote a good commit message & description [see guide below].
- [ ] Commit message starts with `[Resolve #issue-number]`.
- [x] Added/Updated unit tests.
- [ ] Added/Updated integration tests (if applicable).
- [x] All unit tests (`make test`) are passing.
- [X] Used the same coding conventions as the rest of the project.
- [X] The new code passes pre-commit validations (`pre-commit run --all-files`).
- [X] The PR relates to _only_ one subject with a clear title.
      and description in grammatically correct, complete sentences.

## Approver/Reviewer Checklist

- [ ] Before merge squash related commits.

## Other Information

[Guide to writing a good commit](http://chris.beams.io/posts/git-commit/)

### CODE REVIEW

**Comment by zaro0508** [comment]
one of the build failed @tarkatronic

**Comment by tarkatronic** [comment]
> one of the build failed @tarkatronic

Taking a look at it now. Looks like I missed a build step on one of the CircleCI jobs. Should be able to fix it up quickly.

**Comment by tarkatronic** [comment]
@zaro0508 The CI flow should be fixed now. The code wasn't getting checked out before it attempted to build docs. Whoops!

**Review by zxiiro — DISMISSED** [review]

**Comment by ngfgrant** [comment]
I know I have been less involved recently but the changes here are sweeping and just a glance over the request makes me really nervous. 

We are swapping setuptools for a dependency on poetry and I would argue gaining very little.

Honestly, I don't think it is worth it. Sorry to be negative and really _really_ value people who are motivated enough to contribute (so thank you). 

I will let the others pitch in...

**Comment by zaro0508** [comment]
I disagree with @ngfgrant.  While we may gain very little initially these types of improvements pay off in the long term.  I am willing to accept this contribution as long as it gets thorough testing and I'm willing to help with that.

**Comment by zaro0508** [comment]
This PR is stale a new attempt has been made in PR #1323

**Pull request closed without merging**
