### PR TITLE
Resolve #982 add examples of on_failure

### LINKED ISSUE #982: Documentation should provide examples for on_failure option
Documentation provides a link to AWS documentation, but it should include a few examples on how to use `on_failure`. This makes it easier to search on a search engine.

#980  addresses this.

### PR DESCRIPTION
**Pull request by felipe1982**
Resolve #982 

this makes it easy to search for "rollback" on google.

add three valid examples of values for the `on_failure` key. This makes it easier to search in google for **sceptre rollback**.

## PR Checklist

- [x] Wrote a good commit message & description [see guide below].
- [x] Commit message starts with `[Resolve #issue-number]`.
- [ ] Added/Updated unit tests.
- [ ] Added/Updated integration tests (if applicable).
- [ ] All unit tests (`make test`) are passing.
- [x] Used the same coding conventions as the rest of the project.
- [x] The new code passes flake8 (`make lint`) checks.
- [x] The PR relates to _only_ one subject with a clear title.
      and description in grammatically correct, complete sentences.

## Approver/Reviewer Checklist

- [ ] Before merge squash related commits.

## Other Information

[Guide to writing a good commit](http://chris.beams.io/posts/git-commit/)

### CODE REVIEW

**Review by zxiiro — APPROVED** [review]
Good idea. Saves having to click another link just to see available options.

**Comment by zaro0508** [comment]
I'm not sure I agree @zxiiro.  I think this would cause a maintenance burden on sceptre.  IMO it's better to reference the source than to be the source.

**Comment by zxiiro** [comment]
> I'm not sure I agree @zxiiro. I think this would cause a maintenance burden on sceptre. IMO it's better to reference the source than to be the source.

Upstream will always be the primary source of truth but I also don't think it's harmful to list the the valid options here on a best effort basis. I also believe the `OnFailure` parameter is unlikely to change very often if at all.

**Comment by zaro0508** [comment]
What are your thought @craighurley ?

**Comment by craighurley** [comment]
For me, in this case the wording makes it clear that they are examples and the source is the AWS docs, and I think those example values are unlikley to be changed by AWS in the future.

**Review by zaro0508 — APPROVED** [review]

**Pull request merged**
