### PR TITLE
Resolve #1163 update doc link to new domain

### LINKED ISSUE #1163: The Documentation Links in README.md Display a 404 'Site not found' Error
### Subject of the issue
All of  the Sceptre documentation links in `README.md` and the [sceptre.cloudreach.com](https://sceptre.cloudreach.com) link in the GitHub 'About' box display a 404 'Site not found error.

Should these links should be updated to relevant pages within [docs.sceptre-project.org](https://docs.sceptre-project.org/)?

### PR DESCRIPTION
**Pull request by zainulabidin302**
Updating links in docs and elsewhere to new domain

## PR Checklist

- [x] Wrote a good commit message & description [see guide below].
- [x] Commit message starts with `[Resolve #issue-number]`.
- [x] Added/Updated unit tests.
- [x] Added/Updated integration tests (if applicable).
- [x] All unit tests (`make test`) are passing.
- [x] Used the same coding conventions as the rest of the project.
- [x] The new code passes pre-commit validations (`pre-commit run --all-files`).
- [x] The PR relates to _only_ one subject with a clear title.
      and description in grammatically correct, complete sentences.

## Approver/Reviewer Checklist

- [x] Before merge squash related commits.

## Other Information

[Guide to writing a good commit](http://chris.beams.io/posts/git-commit/)

### CODE REVIEW

**Comment by zainulabidin302** [comment]
Hi @jfalkenstein, the docs links are now pointing to new domain name. Have a look.

**Comment by jfalkenstein** [comment]
@zaro0508 , this looks good to me. I'm wondering why the CircleCI build didn't fire on this PR, though.

**Review by jfalkenstein — APPROVED** [review]
Looks good to me. Thanks for doing this!

**Comment by zaro0508** [comment]
> @zaro0508 , this looks good to me. I'm wondering why the CircleCI build didn't fire on this PR, though.

@jfalkenstein I've noticed that GH won't trigger builds for PR from people that are not members of this GH ORG.  @zainulabidin302 is not a part of the Sceptre GH Org yet, https://github.com/orgs/Sceptre/people/pending_invitations

I'm not sure how to change it so that GH will trigger for any PR that comes in.

**Review by zaro0508 — APPROVED** [review]

**Pull request merged**
