### PR TITLE
WIP: add support for python 3.10

### PR DESCRIPTION
**Pull request by zaro0508**

### CODE REVIEW

**Comment by zaro0508** [comment]
tests are failing on the below check which seems to indicate that yaml load and json load are not generating the exact same results.

expected
```
{'Outputs': {'VpcId': {'Description': 'New VPC ID', 'Value': {'Ref': 'VirtualPrivateCloud'}}}, 'Parameters': {'CidrBlock': {'Default': '10.0.0.0/16', 'Type': 'String'}}, 'Resources': {'IGWAttachment': {'Properties': {'InternetGatewayId': {'Ref': 'InternetGateway'}, 'VpcId': {'Ref': 'VirtualPrivateCloud'}}, 'Type': 'AWS::EC2::VPCGatewayAttachment'}, 'InternetGateway': {'Type': 'AWS::EC2::InternetGateway'}, 'VirtualPrivateCloud': {'Properties': {'CidrBlock': {'Ref': 'CidrBlock'}, 'EnableDnsHostnames': 'true', 'EnableDnsSupport': 'true', 'InstanceTenancy': 'default'}, 'Type': 'AWS::EC2::VPC'}}}
```

actual
```
{'Outputs': {'VpcId': {'Description': 'New VPC ID', 'Value': {'Ref': 'VirtualPrivateCloud'}}}, 'Parameters': {'CidrBlock': {'Default': '10.0.0.0/16', 'Type': 'String'}}, 'Resources': {'IGWAttachment': {'Properties': {'InternetGatewayId': {'Ref': 'InternetGateway'}, 'VpcId': {'Ref': 'VirtualPrivateCloud'}}, 'Type': 'AWS::EC2::VPCGatewayAttachment'}, 'InternetGateway': {'Type': 'AWS::EC2::InternetGateway'}, 'VirtualPrivateCloud': {'Properties': {'CidrBlock': {'Ref': 'CidrBlock'}, 'EnableDnsHostnames': True, 'EnableDnsSupport': True, 'InstanceTenancy': 'default'}, 'Type': 'AWS::EC2::VPC'}}}
```

**Comment by jfalkenstein** [comment]
@zaro0508 I've made the changes to support later versions of packaging. If you pull master, you should get those and hopefully any issues caused by that old version on this or will be resolved.

**Comment by jfalkenstein** [comment]
@zaro0508 , you should close this, right?

**Comment by zaro0508** [comment]
resolved with PR #1227

**Pull request closed without merging**
