### PR TITLE
[Resolves #978] Only install typing on Python<3.5

### LINKED ISSUE #978: typing should not be installed for Python >= 3.5
`typing` is in the standard library since Python 3.5. Installing it alongside the standard library version causes the following error:
```
AttributeError: type object 'Callable' has no attribute '_abc_registry'
```

See https://github.com/python/typing/issues/573 for additional context and other packages in which this issue has arisen.

### PR DESCRIPTION
**Pull request by gabriellesc**
This PR constrains the installation of `typing` to Python<3.5, since it is included in the standard library as of 3.5 and causes issues if installed alongside the standard library version.

## PR Checklist

- [x] Wrote a good commit message & description [see guide below].
- [x] Commit message starts with `[Resolve #issue-number]`.
- [ ] Added/Updated unit tests.
- [ ] Added/Updated integration tests (if applicable).
- [ ] All unit tests (`make test`) are passing.
- [x] Used the same coding conventions as the rest of the project.
- [ ] The new code passes flake8 (`make lint`) checks.
- [x] The PR relates to _only_ one subject with a clear title.
      and description in grammatically correct, complete sentences.

## Approver/Reviewer Checklist

- [ ] Before merge squash related commits.

## Other Information

[Guide to writing a good commit](http://chris.beams.io/posts/git-commit/)

### CODE REVIEW

**Review by zxiiro — APPROVED** [review]

**Comment by zaro0508** [comment]
maybe should just remove typing altogether since sceptre currently only supports python 3.6 and 3.7?  https://github.com/Sceptre/sceptre/blob/master/tox.ini#L2

**Comment by chrono** [comment]
Anything else needed to merge this?

**Comment by ykhalyavin** [comment]
> maybe should just remove typing altogether since sceptre currently only supports python 3.6 and 3.7? https://github.com/Sceptre/sceptre/blob/master/tox.ini#L2

Makes sense

**Comment by tarkatronic** [comment]
@gabriellesc Do you have time to update this and fully remove `typing`?

@zaro0508 If Gabrielle is not able to get this updated, would you be willing to merge another PR to take care of this? And would there be a possibility of a bugfix release to include this update?

This has become a hard blocker for me, as I cannot concurrently install `sceptre` and `black` into my projects.

**Comment by zaro0508** [comment]
> @zaro0508 If Gabrielle is not able to get this updated, would you be willing to merge another PR to take care of this? And would there be a possibility of a bugfix release to include this update?

yes @tarkatronic, willing to merge another PR for this however we are having difficulties with making a release at this moment.  we are having discussions and trying to resolve in the #sceptre slack channel.

**Comment by craighurley** [comment]
Hi @tarkatronic , to work around module conflicts I run sceptre in a container. If this is something that would work for you in this case, have a look at https://github.com/craighurley/docker-sceptre

**Comment by gabriellesc** [comment]
Fully removed the `typing` dependency as suggested! Let me know if there is anything I missed.

**Review by zaro0508 — APPROVED** [review]

**Review by tarkatronic — APPROVED** [review]

**Pull request merged**
