### PR TITLE
[Resolves #881] Parse and format objects when listing with '--output text'

### LINKED ISSUE #881: list output command fails with TypeError
I'm using sceptre v2.3.0.  When i run sceptre to list outputs i get the following error: "TypeError: sequence item 0: expected str instance, dict found"

```
> sceptre launch --yes prod/bug.yaml
[2020-02-14 11:13:05] - prod/bug - Launching Stack
[2020-02-14 11:13:05] - prod/bug - Stack is in the PENDING state
[2020-02-14 11:13:05] - prod/bug - Creating Stack
[2020-02-14 11:13:07] - prod/bug bug AWS::CloudFormation::Stack CREATE_IN_PROGRESS User Initiated
[2020-02-14 11:13:11] - prod/bug S3Bucket AWS::S3::Bucket CREATE_IN_PROGRESS
[2020-02-14 11:13:11] - prod/bug S3Bucket AWS::S3::Bucket CREATE_IN_PROGRESS Resource creation Initiated
[2020-02-14 11:13:32] - prod/bug S3Bucket AWS::S3::Bucket CREATE_COMPLETE
[2020-02-14 11:13:36] - prod/bug bug AWS::CloudFormation::Stack CREATE_COMPLETE

> sceptre list outputs prod/bug.yaml
Traceback (most recent call last):
  File "/Users/zaro0508/.virtualenvs/py36-default/bin/sceptre", line 8, in <module>
    sys.exit(cli())
  File "/Users/zaro0508/.virtualenvs/py36-default/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/Users/zaro0508/.virtualenvs/py36-default/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/Users/zaro0508/.virtualenvs/py36-default/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/zaro0508/.virtualenvs/py36-default/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/zaro0508/.virtualenvs/py36-default/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/zaro0508/.virtualenvs/py36-default/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/Users/zaro0508/.virtualenvs/py36-default/lib/python3.6/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/zaro0508/.virtualenvs/py36-default/lib/python3.6/site-packages/sceptre/cli/helpers.py", line 36, in decorated
    return func(*args, **kwargs)
  File "/Users/zaro0508/.virtualenvs/py36-default/lib/python3.6/site-packages/sceptre/cli/list.py", line 92, in list_outputs
    write(responses, context.output_format)
  File "/Users/zaro0508/.virtualenvs/py36-default/lib/python3.6/site-packages/sceptre/cli/helpers.py", line 80, in write
    output = "---\n".join(var)
TypeError: sequence item 0: expected str instance, dict found
```

sceptre bug.yaml template:
``` 
template_path: bug.yaml
stack_name: bug
```

Cloudformation template:
```
Description: test template
AWSTemplateFormatVersion: 2010-09-09
Resources:
  S3Bucket:
    Type: "AWS::S3::Bucket"
Outputs:
  S3Bucket:
    Value: !Ref S3Bucket
    Export:
      Name: !Sub '${AWS::Region}-${AWS::StackName}-S3Bucket'
```

### PR DESCRIPTION
**Pull request by n2taylor**
This PR is a fix for https://github.com/Sceptre/sceptre/issues/881.

Instead of just trying to spit out unstructured text, I've tried to do some basic formatting of the output into columns. I'd appreciate some feedback on the approach here as I did not try doing any advanced formatting (coloring etc.) other than 
to make it readable. The output looks like this:

```
$ sceptre --output text list resources shared
Stack                     LogicalResourceId    PhysicalResourceId

shared/iam/deploy-user    AccessKey            AKIA_SOME_KEY
shared/iam/deploy-user    AccessSecret         arn:aws:secretsmanager:us-east-2:00000000000:secret:some_user_access_key
shared/iam/deploy-user    DeployUser           ThirdPartyDeploy
shared/dashboard/repo     Dashboard            dashboard
shared/dashboard/repo     DashboardNginx       dashboard-nginx
```

It also fixes `sceptre list outputs`:

```
Stack                    OutputKey         OutputValue        ExportName

shared/dashboard/repo    DashboardNginx    dashboard-nginx    dashboard-ecr-redash-nginx
shared/dashboard/repo    Dashboard         dashboard          dashboard-ecr-redash
```

### CODE REVIEW

**Comment by zaro0508** [comment]
I believe py27 tests are failing due to #921

**Comment by n2taylor** [comment]
will do

**Comment by zaro0508** [comment]
any chance you will be able to add tests anytime soon @n2taylor ?

**Comment by n2taylor** [comment]
Hi, I'll give it a shot hopefully this week.... got sidetracked with other things

**Review by zaro0508 — DISMISSED** [review]
I have tested this PR and it looks good.  I have also added tests for it in PR #960.  Could you please take a look @ngfgrant ?

**Comment by n2taylor** [comment]
Thanks for adding those tests, they look good to me... I rebased the branch to latest master.

**Pull request merged**
