### PR TITLE
[Resolves #841] Add documented name as entry point for ASG hook

### LINKED ISSUE #841: ASGScalingProcesses registered as 'asg_scheduled_actions', expected to be 'asg_scaling_processes'
I noticed that the default hook for ASG processes is registered as `            "asg_scheduled_actions ="` and not as `asg_scaling_processes`, see https://github.com/Sceptre/sceptre/blob/b7585fd7bf9607230f9d4324166b49cd59cab3ee/setup.py#L59

In the docs (2.2.1) and also the code (https://github.com/Sceptre/sceptre/blob/9a36309ed1daa15ef65504fa550adf161e6d7c6f/sceptre/hooks/asg_scaling_processes.py#L39-L40) it's referenced as `asg_scaling_processes`, but using `!asg_scaling_processes` in `hooks` results in:
```
yaml.constructor.ConstructorError: could not determine a constructor for the tag '!asg_scaling_processes'
  in "<unicode string>", line 40, column 7:
        - !asg_scaling_processes 'suspend: ...
          ^
```

### PR DESCRIPTION
**Pull request by iainelder**
[Your PR description here]

## PR Checklist

- [ ] Wrote a good commit message & description [see guide below].
- [ ] Commit message starts with `[Resolve #issue-number]`.
- [ ] Added/Updated unit tests.
- [ ] Added/Updated integration tests (if applicable).
- [ ] All unit tests (`poetry run tox`) are passing.
- [ ] Used the same coding conventions as the rest of the project.
- [ ] The new code passes pre-commit validations (`poetry run pre-commit run --all-files`).
- [ ] The PR relates to _only_ one subject with a clear title.
      and description in grammatically correct, complete sentences.

## Approver/Reviewer Checklist

- [ ] Before merge squash related commits.

## Other Information

[Guide to writing a good commit](http://chris.beams.io/posts/git-commit/)

### CODE REVIEW

**Comment by iainelder** [comment]
[My comment on #841](https://github.com/Sceptre/sceptre/issues/841#issuecomment-1732367411) explains the change.

Can you think of a way to test this in the current framework? Do we need to?

I don't think a unit test isn't appropriate for this change. A test would need a real template as input and it would need to check the behavior of the CLI.

If we are going to deprecate the old name, should detect its use and show a warning?

A deprecation notice would complicate the hook implementation, and may not be worth the hassle. A user can transition with a global search and replace.

**Comment by iainelder** [comment]
[My dev notes for the change](https://github.com/iainelder/sceptre-dev-notes/blob/main/dev-notes/update-asg-hook.md).

**Review by zaro0508 — COMMENTED** [review]
i think we should just remove the old name (`asg_scheduled_action`) in this PR and merge it when we do the next major release (5.0).

**Comment by iainelder** [comment]
That makes sense to me. I suppose when you prepare the major release you can note it as a breaking change.

I've pushed another commit that removed the old name.

How does it look?

**Review by zaro0508 — APPROVED** [review]

**Comment by iainelder** [comment]
@alexharv074 requested that it remain compatible with the current release family 4.0.

**Pull request merged**
