### PR TITLE
[Resolve #1464] Display launch order

### LINKED ISSUE #1464: List proposed order of operations for `sceptre launch`
### Subject of the issue

When issuing `sceptre launch`, it would be useful to see the stacks that will be deployed, in the order they will be deployed, similar to the functionality provided by `sceptre delete`. This would be especially convenient when working with large projects with complex dependency trees.

### Your environment
* version of sceptre (sceptre --version): 4.4.2
* version of python (python --version): 3.11
* which OS/distro: MacOS

### Expected behaviour

Something akin to:

```
> sceptre launch s3
The following stacks, in the following order, will be deployed:
s3/bucket
s3/bucket-policy

Do you want to launch 's3' [y/N]:
```

### Actual behaviour

```
> sceptre launch s3
Do you want to launch 's3' [y/N]:
```

### PR DESCRIPTION
**Pull request by p7-mark**
Resolves #1464.

image

## PR Checklist

- [X] Wrote a good commit message & description [see guide below].
- [X] Commit message starts with `[Resolve #issue-number]`.
- [ ] Added/Updated unit tests.
- [ ] Added/Updated integration tests (if applicable).
- [X] All unit tests (`poetry run tox`) are passing.
- [X] Used the same coding conventions as the rest of the project.
- [X] The new code passes pre-commit validations (`poetry run pre-commit run --all-files`).
- [X] The PR relates to _only_ one subject with a clear title.
      and description in grammatically correct, complete sentences.

## Approver/Reviewer Checklist

- [ ] Before merge squash related commits.

## Other Information

[Guide to writing a good commit](http://chris.beams.io/posts/git-commit/)

### CODE REVIEW

**Comment by alexharv074** [comment]
@p7-mark How do you handle the case of `launch -y` here. Those launching stacks in a CI pipeline using full automation need to be assured that this change does not break that automation.

**Comment by p7-mark** [comment]
> @p7-mark How do you handle the case of `launch -y` here. Those launching stacks in a CI pipeline using full automation need to be assured that this change does not break that automation.

@alexharv074 when using `launch -y`, the order of operations is simply printed, and then the launch command is executed without confirmation.

In this example, I run `launch -y` against a stack group with two stacks (one with `obsolete: true`):
```
sceptre launch s3 -y
* During launch, the following stacks will be skipped, neither created nor updated:
s3/bucket-policy

The following operations will occur, in the following order:
Deploy: s3/bucket
Skip:   s3/bucket-policy

[2024-05-27 07:34:22] - s3/bucket - Launching Stack
[2024-05-27 07:34:23] - s3/bucket - Stack is in the PENDING state
[2024-05-27 07:34:23] - s3/bucket - Creating Stack
[2024-05-27 07:34:23] - s3/bucket localtest-s3-bucket AWS::CloudFormation::Stack CREATE_IN_PROGRESS User Initiated
[2024-05-27 07:34:27] - s3/bucket Bucket AWS::S3::Bucket CREATE_IN_PROGRESS
[2024-05-27 07:34:27] - s3/bucket Bucket AWS::S3::Bucket CREATE_IN_PROGRESS Resource creation Initiated
...
```

**Comment by alexharv074** [comment]
@p7-mark Thanks I can live with this although I feel like the output in the `launch -y` case is a bit inconsistent with the original design i.e. not quite Sceptre-y enough! I also think your new code probably belongs in a new private method; it feels to me as if there is too much going on in the `print_operations` method now.

**Comment by alexharv074** [comment]
@p7-mark I have been using this a while now and feel that some work is needed to make the output consistent and clean. During delete I see this:

Screenshot 2024-06-10 at 2 24 41 pm

During launch I then see this:

Screenshot 2024-06-10 at 2 24 51 pm

Similarly, the implementation in the code is inconsistent. You have:

Screenshot 2024-06-10 at 2 26 41 pm

Elsewhere:

Screenshot 2024-06-10 at 2 33 18 pm

Screenshot 2024-06-10 at 2 33 18 pm

**Review by alexharv074 — CHANGES_REQUESTED** [review]
See comments.

**Comment by alexharv074** [comment]
@p7-mark any thoughts on the above?

**Comment by alexharv074** [comment]
It seems like the author has abandoned this PR, so I'm closing it. @p7-mark please feel free to open a new PR if you ever return to this!

**Pull request closed without merging**
