### PR TITLE
[Resolve #546] select command stacks based on exact stack-group name

### LINKED ISSUE #546: launching/deleting stackgroup whose name is substring of other stackgroup will also launch/delete other stackgroup
I have the following stack config structure

env/s1.yaml
```
template_path: mystack.template.yaml
parameters:
  Name: envs1
  Value: envs1
```

env1/s1.yaml
```
template_path: mystack.template.yaml
parameters:
  Name: env1s1
  Value: env1s1
```

When I run the command `sceptre launch env` both env/s1 and env1/s1 are launched even if they are unrelated. Similarly when I run `sceptre delete env` both env/s1 and env1/s1 are deleted even if they are unrelated.

I also tested the scenario renaming env to env2 and in this case env1 and env2 can be launched separately. Then I also tested renaming env1 to env-sec, in this scenario, both env and env-sec launched simultaneously when trying to launch env only.

How do I launch env without launching env1?

### PR DESCRIPTION
**Pull request by cornerman**
When specifying a `command_path` for cli operations, commands will be executed on all stack-groups which share a prefix with `command_path`. So, if you have two configs `env1` and `env2`, but then provide `env` as your `command_path`, both `env1` and `env2` will be executed.

In my opinion, `env` is not a valid stack-group and should therefore not start anything. We should either specify `env1` or `env2` expicitly or alternatively group them under one common directory `my-envs` when you want to launch stack together.

## PR Checklist

- [x] Wrote a good commit message & description [see guide below].
- [x] Commit message starts with `[Resolve #issue-number]`.
- [x] Added/Updated unit tests.
- [ ] Added/Updated integration tests (if applicable).
- [ ] All unit tests (`make test`) are passing.
- [x] Used the same coding conventions as the rest of the project.
- [x] The new code passes flake8 (`make lint`) checks.
- [x] The PR relates to _only_ one subject with a clear title.
      and description in grammatically correct, complete sentences.

## Approver/Reviewer Checklist

- [ ] Before merge squash related commits.

## Other Information

[Guide to writing a good commit](http://chris.beams.io/posts/git-commit/)

### CODE REVIEW

**Comment by ngfgrant** [comment]
@cornerman thanks for the PR. LGTM but I'd like someone with windows to test this if they could basically I am intrigued as to whether the use of `sep` will cause issues in Windows. I don't think it will but worth double checking. Maybe @lukeplausin or @mike-rsi if you get sometime to checkout this branch?

**Comment by cornerman** [comment]
We might want to add a check for yaml files. If you have a config file `config/folder/resource.yaml`, you should be able to select this stack with either `sceptre status folder/resource.yaml` or `sceptre status folder/resource`. With this PR, currently only the latter would work.

**Comment by craighurley** [comment]
Would love to see this make it into the next release.  This issue has tripped up colleagues on my team, luckily in non-prod environments 😄.

**Comment by ngfgrant** [comment]
Guys its my bad for letting this stay open as long as it has. Definitely need to get this merged and I am happy with this PR as it is. As per my original comment there may be some windows issues with sep but I am pretty sure there won't be.

@cornerman  if you have time could you rebase this off master and resolve the conflict in `test_config_reader.py`? If not let me know and I'll help out.

**Comment by rseuchter** [comment]
> @cornerman if you have time could you rebase this off master and resolve the conflict in `test_config_reader.py`? If not let me know and I'll help out.

I took the liberty of rebasing this. Please check https://github.com/rseuchter/sceptre/commit/f5a5181a3a16d0216473f5534bf212e63a499fd1
(I have no idea if or how I can add this to the existing PR #731) 

An hour or two ago, I ran into this bug with a colleague. While we found a workaround it caused some serious concern. After realizing this has been lying around for so long I thought I rather help get this resolved.

**Comment by cornerman** [comment]
@rseuchter Thank you! That is great. I just reset my branch to your commit and pushed!

@ngfgrant This PR is now rebased

**Comment by rseuchter** [comment]
This PR has been stale. Still, I feel the underlying issue is critical.
The [build says](https://github.com/Sceptre/sceptre/pull/731/checks?check_run_id=522422729) it was _unauthorized_. I don't think it's related to the PR itself.

Any ideas @ngfgrant?

**Comment by ngfgrant** [comment]
I’m going to get to this and others this weekend. Unauthorised makes sense (to me).

**Pull request merged**
