### PR TITLE
[Resolves #1107] Documenting the iam_role config

### LINKED ISSUE #1107: iam_role is not a documented configuration
### Subject of the issue
Sceptre supports an `iam_role` configuration that is used for assuming that role for any actions taken within that stack / stackgroup. However, this configuration is like a "secret feature"... it's not documented at all, in neither the Stack nor StackGroup config pages.

### PR DESCRIPTION
**Pull request by jfalkenstein**
This adds documentation for the `iam_role` configuration to the StackGroup docs page, which was described as needed in #1107 

## PR Checklist

- [x] Wrote a good commit message & description [see guide below].
- [x] Commit message starts with `[Resolve #issue-number]`.
- [x] Added/Updated unit tests.
- [x] Added/Updated integration tests (if applicable).
- [x] All unit tests (`make test`) are passing.
- [x] Used the same coding conventions as the rest of the project.
- [x] The new code passes pre-commit validations (`pre-commit run --all-files`).
- [x] The PR relates to _only_ one subject with a clear title.
      and description in grammatically correct, complete sentences.

## Approver/Reviewer Checklist

- [ ] Before merge squash related commits.

## Other Information

[Guide to writing a good commit](http://chris.beams.io/posts/git-commit/)

### CODE REVIEW

**Review by craighurley — COMMENTED** [review]
How is "iam_role" different to "profile"?

**Comment by jfalkenstein** [comment]
@craighurley "profile" requires you to have a specifically configured aws profile setup locally. However, `iam_role` is a role that you can use that profile to _assume_. 

For example: Our Jenkins server has a certain set of permissions. Jenkins' AWS environment is configured for a specific set of permissions. However, for executing Sceptre, I want Jenkins to assume a different role with a different set of permissions.

Could you accomplish the goals of `iam_role` via a profile? Sure, probably. But that requires a very specific local environment configuration. Using the `iam_role` in conjunction with the `profile` would allow you to say: "Using this IAM profile, assume this role with elevated permissions in order to execute this specific StackGroup's actions."

Does that make sense?

**Comment by craighurley** [comment]
It does. Can you that info into the docs?

**Comment by jfalkenstein** [comment]
@craighurley I've improved the documentation to compare/contrast this with the `profile` setting. I also moved it to be documented under "Stack Config" rather than "StackGroup Config" since that is more in line with its actual use. Of course, with the way configs cascade... it's all really one in the same.

**Review by zaro0508 — APPROVED** [review]
thanks for this excellent doc @jfalkenstein.  even i was confused about this :)

**Review by craighurley — APPROVED** [review]

**Pull request merged**
