### PR TITLE
[Resolves #798] complex data for resolvers and hooks

### LINKED ISSUE #798: Non-Scalar Arguments to Hooks/Resolvers
Regression of #140 - this is present in 1.5 but not in 2.
Making this to track an upcoming PR to re-add functionality for passing complex data in as an argument to hooks & resolvers.

cc #329

### PR DESCRIPTION
**Pull request by zaro0508**
Allow hooks and resolvers to take complex data objects as arguments.
This is a port of commit ed681aa9 to Sceptre V2

### CODE REVIEW

**Comment by zaro0508** [comment]
@ngfgrant would you be able give this a review?

**Comment by ngfgrant** [comment]
Have you tested with a demo example?

**Comment by zaro0508** [comment]
@ngfgrant what do you mean `demo example`?  I have tested with my sceptre project.

**Comment by ngfgrant** [comment]
Hi thanks @zaro0508 

I've had a look and things look fine. I've merged in another PR ahead of this so if you could possible update this PR resolving any conflicts (shouldn't be anything meaningful) and I'll get this merged.

**Pull request merged**
