### PR TITLE
Stack Configuration & Parameter List processing Enhancements

### PR DESCRIPTION
**Pull request by njsnx**
This PR provides additional functionality and an enhancement to how Lists are processed when provided as a parameter value.

* Added stack_configuration as an optional argument to accept for sceptre_handler(). This allows templates written in python to get additional information about the stack being built to enhance the capabilities of the Python code generating the template.

* Enhanced list processing when a list of values is provided to a Parameter. If the value provided to a parameter was from a variable which was a list of values, it would treat the list as a single item where as now it will form 1 string from all values in the list. This allows for a combination of variable values from files and static values to be used.

### Example
```yaml
Subnets: {{ var.subnets }} # Wouldn't work before, if var.subnets was itself a list
Subnets: # Wouldn't work before, the string would become [subnet-1234,subnet,1234],subnet-123
  - {{ var.subnets }}
  - subnet-123 
```
## PR Checklist

- [x] Wrote a good commit message & description [see guide below].
- [x] Used the same coding conventions as the rest of the project.
- [x] The new code passes flake8 (`make lint`) checks.
- [ ] Commit message starts with `[Resolve #issue-number]`.
- [ ] Added/Updated unit tests.
- [ ] Added/Updated integration tests (if applicable).
- [ ] All unit tests (`make test`) are passing.
- [ ] The PR relates to _only_ one subject with a clear title.
      and description in grammatically correct, complete sentences.

## Approver/Reviewer Checklist

- [ ] Before merge squash related commits.

## Other Information

[Guide to writing a good commit](http://chris.beams.io/posts/git-commit/)

### CODE REVIEW

**Comment by nmyster** [comment]
@ngfgrant Appreciate this may not follow some of the parts in the commit check list but wanted to get this up to at least figure out how best to place it.

I was unsure how to split out my commit so that I could submit the list processing enhancement into it's own thing and the way that I am doing the new feature to allow stack_configuration to work. 

I can raise 2 Issues to discuss each part of this if that is preferred.

**Comment by nmyster** [comment]
@ngfgrant Looking for input on this PR too. How do we get this into an appropriately tested, "good" commit in your view on what I'm setting out to achieve with this PR. that being, the ability to get the processed stack configuration, in full, into sceptre_handler() as an optional argument (to not break backwards compatibility)

**Comment by ngfgrant** [comment]
Thanks @nmyster will give this a look too soon.

**Comment by euanmaxwell** [comment]
+1

Is there any update on this issue @ngfgrant ?

**Pull request closed without merging**
