### PR TITLE
[Resolves #359] Implements use previous paramater feature

### LINKED ISSUE #359: Don't override existing parameters
```
[failed] create change set custom/oar-ecs-cluster/eu-west-1/ecs-cluster
An error occurred (ValidationError) when calling the CreateChangeSet operation: Parameters: [NexusDockerAuth] must have values
```

We've manually set a `NoEcho` parameter because it contains a secret key. As your documents highlight, we shouldn't commit the value to configuration.

It'd be really helpful if sceptre didn't try and override parameter values if they are not provided, that way we can just lean on the values stored in AWS.

Currently we'd have to fiddle around with CLI arguments and must then store secrets in both AWS and wherever we're running secptre.

### PR DESCRIPTION
**Pull request by RobReus**
Resolves #359 

This new feature will make it possible to create and maintain stacks using Sceptre while also having the possibility to modify parameters outside of Sceptre, without Sceptre then overwriting/reverting these changes.

An example use-case: create and maintain your containerized environment using Sceptre, but after the initial deploy, maintain the Docker image tag using a CICD pipeline. When configuring the image tag parameter correctly, it will be given an initial value upon creation, but updates will not overwrite the value.

It is as simple as this:
```yaml
parameters:
  Param:
    initial_value: "foobar"
    use_previous_value: true
```

It is fully backwards compatible and will not break existing functionality.

## PR Checklist

- [X] Wrote a good commit message & description [see guide below].
- [X] Commit message starts with `[Resolve #issue-number]`.
- [X] Added/Updated unit tests.
- [X] Added/Updated integration tests (if applicable).
- [X] All unit tests (`make test`) are passing.
- [X] Used the same coding conventions as the rest of the project.
- [X] The new code passes flake8 (`make lint`) checks.
- [X] The PR relates to _only_ one subject with a clear title.
      and description in grammatically correct, complete sentences.

## Approver/Reviewer Checklist

- [ ] Before merge squash related commits.

### CODE REVIEW

**Comment by ngfgrant** [comment]
First visual pass - this looks great thanks. I’ll try get hands on with it soon.

**Comment by RobReus** [comment]
@ngfgrant any update on this? Anything that could be done by me or others to speed up the review and release process?

Happy to help where I can.

**Comment by alexharv074** [comment]
@RobReus Are you still using Sceptre and still interested in helping to get this feature merged?

**Comment by RobReus** [comment]
> @RobReus Are you still using Sceptre and still interested in helping to get this feature merged?

Unfortunately I have since moved away from using Sceptre and no longer have the time to work on this. Thanks for checking in though!

**Comment by alexharv074** [comment]
@RobReus  All good. You seem to have done most of the hard work. I'll see if I can adopt the PR!

**Comment by alexharv074** [comment]
Closing in favour of https://github.com/Sceptre/sceptre/pull/1476

**Pull request closed without merging**
