### PR TITLE
Remove classifiers

### PR DESCRIPTION
**Pull request by zaro0508**
Removing classifiers in poetry.toml because poetry will auto generate the classifiers[1]

[1] https://python-poetry.org/docs/pyproject/#classifiers

### CODE REVIEW

**Review by tarkatronic — APPROVED** [review]
Should we remove the `Environment` classifier? I'm not certain that one can be auto-generated either.

**Comment by zaro0508** [comment]
> Should we remove the `Environment` classifier? I'm not certain that one can be auto-generated either.

hmm, the docs just has a general statement that it will auto generate `classifiers`.  how do you know which ones it can and cannot auto generate?

**Comment by tarkatronic** [comment]
> > Should we remove the `Environment` classifier? I'm not certain that one can be auto-generated either.
> 
> hmm, the docs just has a general statement that it will auto generate `classifiers`. how do you know which ones it can and cannot auto generate?

From my understanding of that statement, only the `License` and `Programming Language :: Python :: <version>` classifiers will be auto-generated.

**Comment by zaro0508** [comment]
> From my understanding of that statement, only the `License` and `Programming Language :: Python :: <version>` classifiers will be auto-generated.

ok, so how does poetry infer the license without the classifier? does it look in the root folder for a license file?

**Comment by zaro0508** [comment]
i've fixed the classifier.  take another look @tarkatronic ?

**Review by tarkatronic — APPROVED** [review]
👍

**Pull request merged**
